# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _bishop
else:
    import _bishop

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _bishop.SHARED_PTR_DISOWN
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _bishop.delete_SwigPyIterator

    def value(self):
        return _bishop.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _bishop.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _bishop.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _bishop.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _bishop.SwigPyIterator_equal(self, x)

    def copy(self):
        return _bishop.SwigPyIterator_copy(self)

    def next(self):
        return _bishop.SwigPyIterator_next(self)

    def __next__(self):
        return _bishop.SwigPyIterator___next__(self)

    def previous(self):
        return _bishop.SwigPyIterator_previous(self)

    def advance(self, n):
        return _bishop.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _bishop.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _bishop.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _bishop.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _bishop.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _bishop.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _bishop.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _bishop:
_bishop.SwigPyIterator_swigregister(SwigPyIterator)

class StringArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _bishop.StringArray_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _bishop.StringArray___nonzero__(self)

    def __bool__(self):
        return _bishop.StringArray___bool__(self)

    def __len__(self):
        return _bishop.StringArray___len__(self)

    def __getslice__(self, i, j):
        return _bishop.StringArray___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _bishop.StringArray___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _bishop.StringArray___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _bishop.StringArray___delitem__(self, *args)

    def __getitem__(self, *args):
        return _bishop.StringArray___getitem__(self, *args)

    def __setitem__(self, *args):
        return _bishop.StringArray___setitem__(self, *args)

    def pop(self):
        return _bishop.StringArray_pop(self)

    def append(self, x):
        return _bishop.StringArray_append(self, x)

    def empty(self):
        return _bishop.StringArray_empty(self)

    def size(self):
        return _bishop.StringArray_size(self)

    def swap(self, v):
        return _bishop.StringArray_swap(self, v)

    def begin(self):
        return _bishop.StringArray_begin(self)

    def end(self):
        return _bishop.StringArray_end(self)

    def rbegin(self):
        return _bishop.StringArray_rbegin(self)

    def rend(self):
        return _bishop.StringArray_rend(self)

    def clear(self):
        return _bishop.StringArray_clear(self)

    def get_allocator(self):
        return _bishop.StringArray_get_allocator(self)

    def pop_back(self):
        return _bishop.StringArray_pop_back(self)

    def erase(self, *args):
        return _bishop.StringArray_erase(self, *args)

    def __init__(self, *args):
        _bishop.StringArray_swiginit(self, _bishop.new_StringArray(*args))

    def push_back(self, x):
        return _bishop.StringArray_push_back(self, x)

    def front(self):
        return _bishop.StringArray_front(self)

    def back(self):
        return _bishop.StringArray_back(self)

    def assign(self, n, x):
        return _bishop.StringArray_assign(self, n, x)

    def resize(self, *args):
        return _bishop.StringArray_resize(self, *args)

    def insert(self, *args):
        return _bishop.StringArray_insert(self, *args)

    def reserve(self, n):
        return _bishop.StringArray_reserve(self, n)

    def capacity(self):
        return _bishop.StringArray_capacity(self)
    __swig_destroy__ = _bishop.delete_StringArray

# Register StringArray in _bishop:
_bishop.StringArray_swigregister(StringArray)

class Vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.Vector_swiginit(self, _bishop.new_Vector(*args))
    __swig_destroy__ = _bishop.delete_Vector

    def set(self, vx, vy, vz):
        return _bishop.Vector_set(self, vx, vy, vz)

    def __add__(self, v):
        return _bishop.Vector___add__(self, v)

    def __sub__(self, v):
        return _bishop.Vector___sub__(self, v)

    def __truediv__(self, *args):
        return _bishop.Vector___truediv__(self, *args)
    __div__ = __truediv__



    def __mul__(self, *args):
        return _bishop.Vector___mul__(self, *args)

    def __xor__(self, v):
        return _bishop.Vector___xor__(self, v)

    def __iadd__(self, v):
        return _bishop.Vector___iadd__(self, v)

    def __isub__(self, v):
        return _bishop.Vector___isub__(self, v)

    def __imul__(self, v):
        return _bishop.Vector___imul__(self, v)

    def __itruediv__(self, *args):
        return _bishop.Vector___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __call__(self, v):
        return _bishop.Vector___call__(self, v)

    def X(self):
        return _bishop.Vector_X(self)

    def Y(self):
        return _bishop.Vector_Y(self)

    def Z(self):
        return _bishop.Vector_Z(self)

    def magnitude(self):
        return _bishop.Vector_magnitude(self)

    def unitvector(self):
        return _bishop.Vector_unitvector(self)

    def normalize(self):
        return _bishop.Vector_normalize(self)

    def __eq__(self, v):
        return _bishop.Vector___eq__(self, v)

    def __ne__(self, v):
        return _bishop.Vector___ne__(self, v)

    def __lt__(self, v):
        return _bishop.Vector___lt__(self, v)

    def __le__(self, v):
        return _bishop.Vector___le__(self, v)

    def __gt__(self, v):
        return _bishop.Vector___gt__(self, v)

    def __ge__(self, v):
        return _bishop.Vector___ge__(self, v)

    def __str__(self):
        return _bishop.Vector___str__(self)

# Register Vector in _bishop:
_bishop.Vector_swigregister(Vector)

class Matrix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.Matrix_swiginit(self, _bishop.new_Matrix(*args))
    __swig_destroy__ = _bishop.delete_Matrix

    def __call__(self, a, b):
        return _bishop.Matrix___call__(self, a, b)

    def __add__(self, v):
        return _bishop.Matrix___add__(self, v)

    def __sub__(self, v):
        return _bishop.Matrix___sub__(self, v)

    def __truediv__(self, *args):
        return _bishop.Matrix___truediv__(self, *args)
    __div__ = __truediv__



    def __mul__(self, *args):
        return _bishop.Matrix___mul__(self, *args)

    def __iadd__(self, v):
        return _bishop.Matrix___iadd__(self, v)

    def __isub__(self, v):
        return _bishop.Matrix___isub__(self, v)

    def __imul__(self, *args):
        return _bishop.Matrix___imul__(self, *args)

    def __itruediv__(self, *args):
        return _bishop.Matrix___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __eq__(self, v):
        return _bishop.Matrix___eq__(self, v)

    def __ne__(self, v):
        return _bishop.Matrix___ne__(self, v)

    def __lt__(self, v):
        return _bishop.Matrix___lt__(self, v)

    def __le__(self, v):
        return _bishop.Matrix___le__(self, v)

    def __gt__(self, v):
        return _bishop.Matrix___gt__(self, v)

    def __ge__(self, v):
        return _bishop.Matrix___ge__(self, v)

    def inverse(self):
        return _bishop.Matrix_inverse(self)

    def transpose(self):
        return _bishop.Matrix_transpose(self)

    def det(self):
        return _bishop.Matrix_det(self)

    def trace(self):
        return _bishop.Matrix_trace(self)

    def exp(self):
        return _bishop.Matrix_exp(self)

    def setExpRange(self, n):
        return _bishop.Matrix_setExpRange(self, n)

    def getExpRange(self, n):
        return _bishop.Matrix_getExpRange(self, n)

    def sinch(self):
        return _bishop.Matrix_sinch(self)

    def Get(self, a, b):
        return _bishop.Matrix_Get(self, a, b)

    def Set(self, a, b, value):
        return _bishop.Matrix_Set(self, a, b, value)

    def __str__(self):
        return _bishop.Matrix___str__(self)

# Register Matrix in _bishop:
_bishop.Matrix_swigregister(Matrix)

class Camera(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.Camera_swiginit(self, _bishop.new_Camera())
    __swig_destroy__ = _bishop.delete_Camera

    def setEyeViewUp(self, eye, view, up):
        return _bishop.Camera_setEyeViewUp(self, eye, view, up)

    def eye(self):
        return _bishop.Camera_eye(self)

    def up(self):
        return _bishop.Camera_up(self)

    def view(self, *args):
        return _bishop.Camera_view(self, *args)

    def XY(self, P, x, y):
        return _bishop.Camera_XY(self, P, x, y)

    def XYZ(self, P, x, y, z):
        return _bishop.Camera_XYZ(self, P, x, y, z)

    def setFov(self, fov):
        return _bishop.Camera_setFov(self, fov)

    def fov(self):
        return _bishop.Camera_fov(self)

    def setAspectRatio(self, ar):
        return _bishop.Camera_setAspectRatio(self, ar)

    def aspectRatio(self):
        return _bishop.Camera_aspectRatio(self)

    def setNearPlane(self, n):
        return _bishop.Camera_setNearPlane(self, n)

    def nearPlane(self):
        return _bishop.Camera_nearPlane(self)

    def setFarPlane(self, n):
        return _bishop.Camera_setFarPlane(self, n)

    def farPlane(self):
        return _bishop.Camera_farPlane(self)

    def isVisible(self, P):
        return _bishop.Camera_isVisible(self, P)

    def __str__(self):
        return _bishop.Camera___str__(self)

# Register Camera in _bishop:
_bishop.Camera_swigregister(Camera)

class Color(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.Color_swiginit(self, _bishop.new_Color(*args))
    __swig_destroy__ = _bishop.delete_Color

    def set(self, vx, vy, vz, vw):
        return _bishop.Color_set(self, vx, vy, vz, vw)

    def __add__(self, *args):
        return _bishop.Color___add__(self, *args)

    def __sub__(self, *args):
        return _bishop.Color___sub__(self, *args)

    def __mul__(self, *args):
        return _bishop.Color___mul__(self, *args)

    def __truediv__(self, *args):
        return _bishop.Color___truediv__(self, *args)
    __div__ = __truediv__



    def __iadd__(self, *args):
        return _bishop.Color___iadd__(self, *args)

    def __isub__(self, *args):
        return _bishop.Color___isub__(self, *args)

    def __imul__(self, *args):
        return _bishop.Color___imul__(self, *args)

    def __itruediv__(self, *args):
        return _bishop.Color___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __call__(self, v):
        return _bishop.Color___call__(self, v)

    def X(self):
        return _bishop.Color_X(self)

    def Y(self):
        return _bishop.Color_Y(self)

    def Z(self):
        return _bishop.Color_Z(self)

    def W(self):
        return _bishop.Color_W(self)

    def red(self):
        return _bishop.Color_red(self)

    def green(self):
        return _bishop.Color_green(self)

    def blue(self):
        return _bishop.Color_blue(self)

    def alpha(self):
        return _bishop.Color_alpha(self)

    def __eq__(self, v):
        return _bishop.Color___eq__(self, v)

    def __ne__(self, v):
        return _bishop.Color___ne__(self, v)

    def __str__(self):
        return _bishop.Color___str__(self)

# Register Color in _bishop:
_bishop.Color_swigregister(Color)


def log(c):
    return _bishop.log(c)

def pow(c, g):
    return _bishop.pow(c, g)

def __add__(v, c):
    return _bishop.__add__(v, c)

def __truediv__(v, c):
    return _bishop.__truediv__(v, c)

def __sub__(*args):
    return _bishop.__sub__(*args)
class VolumeBase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.VolumeBase_swiginit(self, _bishop.new_VolumeBase())
    __swig_destroy__ = _bishop.delete_VolumeBase

    def addAttribute(self, name, value):
        return _bishop.VolumeBase_addAttribute(self, name, value)

    def attribute(self, name):
        return _bishop.VolumeBase_attribute(self, name)

# Register VolumeBase in _bishop:
_bishop.VolumeBase_swigregister(VolumeBase)

class FDGradHandler(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.FDGradHandler_swiginit(self, _bishop.new_FDGradHandler())
    __swig_destroy__ = _bishop.delete_FDGradHandler

    def setNbTerms(self, n):
        return _bishop.FDGradHandler_setNbTerms(self, n)

    def nbTerms(self):
        return _bishop.FDGradHandler_nbTerms(self)

    def setStep(self, *args):
        return _bishop.FDGradHandler_setStep(self, *args)

    def step(self):
        return _bishop.FDGradHandler_step(self)

    def step_x(self):
        return _bishop.FDGradHandler_step_x(self)

    def step_y(self):
        return _bishop.FDGradHandler_step_y(self)

    def step_z(self):
        return _bishop.FDGradHandler_step_z(self)

    def coefficient(self, n):
        return _bishop.FDGradHandler_coefficient(self, n)

# Register FDGradHandler in _bishop:
_bishop.FDGradHandler_swigregister(FDGradHandler)

class ScalarField(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.ScalarField_swiginit(self, _bishop.new_ScalarField(*args))
    __swig_destroy__ = _bishop.delete_ScalarField

    def __str__(self):
        return _bishop.ScalarField___str__(self)

    def __doc__(self):
        return _bishop.ScalarField___doc__(self)

    def __add__(self, e2):
        return _bishop.ScalarField___add__(self, e2)

    def __sub__(self, e2):
        return _bishop.ScalarField___sub__(self, e2)

    def __neg__(self):
        return _bishop.ScalarField___neg__(self)

    def __truediv__(self, *args):
        return _bishop.ScalarField___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, e2):
        return _bishop.ScalarField___xor__(self, e2)

    def __mul__(self, *args):
        return _bishop.ScalarField___mul__(self, *args)

# Register ScalarField in _bishop:
_bishop.ScalarField_swigregister(ScalarField)

class VectorField(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.VectorField_swiginit(self, _bishop.new_VectorField(*args))
    __swig_destroy__ = _bishop.delete_VectorField

    def __str__(self):
        return _bishop.VectorField___str__(self)

    def __doc__(self):
        return _bishop.VectorField___doc__(self)

    def __add__(self, e2):
        return _bishop.VectorField___add__(self, e2)

    def __sub__(self, e2):
        return _bishop.VectorField___sub__(self, e2)

    def __neg__(self):
        return _bishop.VectorField___neg__(self)

    def __truediv__(self, *args):
        return _bishop.VectorField___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, e2):
        return _bishop.VectorField___xor__(self, e2)

    def __mul__(self, *args):
        return _bishop.VectorField___mul__(self, *args)

# Register VectorField in _bishop:
_bishop.VectorField_swigregister(VectorField)

class ColorField(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.ColorField_swiginit(self, _bishop.new_ColorField(*args))
    __swig_destroy__ = _bishop.delete_ColorField

    def __str__(self):
        return _bishop.ColorField___str__(self)

    def __add__(self, e2):
        return _bishop.ColorField___add__(self, e2)

    def __sub__(self, e2):
        return _bishop.ColorField___sub__(self, e2)

    def __neg__(self):
        return _bishop.ColorField___neg__(self)

    def __mul__(self, *args):
        return _bishop.ColorField___mul__(self, *args)

    def __truediv__(self, *args):
        return _bishop.ColorField___truediv__(self, *args)
    __div__ = __truediv__



# Register ColorField in _bishop:
_bishop.ColorField_swigregister(ColorField)

class MatrixField(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.MatrixField_swiginit(self, _bishop.new_MatrixField(*args))
    __swig_destroy__ = _bishop.delete_MatrixField

    def __str__(self):
        return _bishop.MatrixField___str__(self)

    def __doc__(self):
        return _bishop.MatrixField___doc__(self)

    def __add__(self, e2):
        return _bishop.MatrixField___add__(self, e2)

    def __sub__(self, e2):
        return _bishop.MatrixField___sub__(self, e2)

    def __neg__(self):
        return _bishop.MatrixField___neg__(self)

    def __mul__(self, *args):
        return _bishop.MatrixField___mul__(self, *args)

    def __truediv__(self, *args):
        return _bishop.MatrixField___truediv__(self, *args)
    __div__ = __truediv__



# Register MatrixField in _bishop:
_bishop.MatrixField_swigregister(MatrixField)


def SF(v):
    return _bishop.SF(v)

def VF(v):
    return _bishop.VF(v)

def CF(v):
    return _bishop.CF(v)

def MF(v):
    return _bishop.MF(v)
class ScalarVolume(VolumeBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.ScalarVolume_swiginit(self, _bishop.new_ScalarVolume())
    __swig_destroy__ = _bishop.delete_ScalarVolume

    def eval(self, P):
        return _bishop.ScalarVolume_eval(self, P)

    def grad(self, P):
        return _bishop.ScalarVolume_grad(self, P)

    def typelabel(self):
        return _bishop.ScalarVolume_typelabel(self)

    def documentation(self):
        return _bishop.ScalarVolume_documentation(self)
    gradParams = property(_bishop.ScalarVolume_gradParams_get, _bishop.ScalarVolume_gradParams_set)

    def setFDSize(self, nb):
        return _bishop.ScalarVolume_setFDSize(self, nb)

    def setFDStep(self, *args):
        return _bishop.ScalarVolume_setFDStep(self, *args)

# Register ScalarVolume in _bishop:
_bishop.ScalarVolume_swigregister(ScalarVolume)

class VectorVolume(VolumeBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.VectorVolume_swiginit(self, _bishop.new_VectorVolume())
    __swig_destroy__ = _bishop.delete_VectorVolume

    def eval(self, P):
        return _bishop.VectorVolume_eval(self, P)

    def grad(self, P):
        return _bishop.VectorVolume_grad(self, P)

    def typelabel(self):
        return _bishop.VectorVolume_typelabel(self)

    def documentation(self):
        return _bishop.VectorVolume_documentation(self)
    gradParams = property(_bishop.VectorVolume_gradParams_get, _bishop.VectorVolume_gradParams_set)

    def setFDSize(self, nb):
        return _bishop.VectorVolume_setFDSize(self, nb)

    def setFDStep(self, *args):
        return _bishop.VectorVolume_setFDStep(self, *args)

# Register VectorVolume in _bishop:
_bishop.VectorVolume_swigregister(VectorVolume)

class ColorVolume(VolumeBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.ColorVolume_swiginit(self, _bishop.new_ColorVolume())
    __swig_destroy__ = _bishop.delete_ColorVolume

    def eval(self, P):
        return _bishop.ColorVolume_eval(self, P)

    def grad(self, P):
        return _bishop.ColorVolume_grad(self, P)

    def typelabel(self):
        return _bishop.ColorVolume_typelabel(self)

    def documentation(self):
        return _bishop.ColorVolume_documentation(self)
    gradParams = property(_bishop.ColorVolume_gradParams_get, _bishop.ColorVolume_gradParams_set)

    def setFDSize(self, nb):
        return _bishop.ColorVolume_setFDSize(self, nb)

    def setFDStep(self, *args):
        return _bishop.ColorVolume_setFDStep(self, *args)

# Register ColorVolume in _bishop:
_bishop.ColorVolume_swigregister(ColorVolume)

class ScalarFieldBase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.ScalarFieldBase_swiginit(self, _bishop.new_ScalarFieldBase())
    __swig_destroy__ = _bishop.delete_ScalarFieldBase

# Register ScalarFieldBase in _bishop:
_bishop.ScalarFieldBase_swigregister(ScalarFieldBase)

class VectorFieldBase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.VectorFieldBase_swiginit(self, _bishop.new_VectorFieldBase())
    __swig_destroy__ = _bishop.delete_VectorFieldBase

# Register VectorFieldBase in _bishop:
_bishop.VectorFieldBase_swigregister(VectorFieldBase)

class ColorFieldBase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _bishop.ColorFieldBase_swiginit(self, _bishop.new_ColorFieldBase())
    __swig_destroy__ = _bishop.delete_ColorFieldBase

# Register ColorFieldBase in _bishop:
_bishop.ColorFieldBase_swigregister(ColorFieldBase)

class ProgressMeter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nb, ttl):
        _bishop.ProgressMeter_swiginit(self, _bishop.new_ProgressMeter(nb, ttl))

    def update(self):
        return _bishop.ProgressMeter_update(self)
    __swig_destroy__ = _bishop.delete_ProgressMeter

# Register ProgressMeter in _bishop:
_bishop.ProgressMeter_swigregister(ProgressMeter)

class ConstantVolume(ScalarVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, v):
        _bishop.ConstantVolume_swiginit(self, _bishop.new_ConstantVolume(v))
    __swig_destroy__ = _bishop.delete_ConstantVolume

    def eval(self, P):
        return _bishop.ConstantVolume_eval(self, P)

    def grad(self, P):
        return _bishop.ConstantVolume_grad(self, P)

    def typelabel(self):
        return _bishop.ConstantVolume_typelabel(self)

# Register ConstantVolume in _bishop:
_bishop.ConstantVolume_swigregister(ConstantVolume)

class ExpVolume(ScalarVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.ExpVolume_swiginit(self, _bishop.new_ExpVolume(*args))
    __swig_destroy__ = _bishop.delete_ExpVolume

    def eval(self, P):
        return _bishop.ExpVolume_eval(self, P)

    def grad(self, P):
        return _bishop.ExpVolume_grad(self, P)

    def typelabel(self):
        return _bishop.ExpVolume_typelabel(self)

# Register ExpVolume in _bishop:
_bishop.ExpVolume_swigregister(ExpVolume)

class AddVolume(ScalarVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.AddVolume_swiginit(self, _bishop.new_AddVolume(*args))
    __swig_destroy__ = _bishop.delete_AddVolume

    def eval(self, P):
        return _bishop.AddVolume_eval(self, P)

    def grad(self, P):
        return _bishop.AddVolume_grad(self, P)

    def typelabel(self):
        return _bishop.AddVolume_typelabel(self)

# Register AddVolume in _bishop:
_bishop.AddVolume_swigregister(AddVolume)

class SphereVolume(ScalarVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cen, rad):
        _bishop.SphereVolume_swiginit(self, _bishop.new_SphereVolume(cen, rad))
    __swig_destroy__ = _bishop.delete_SphereVolume

    def eval(self, P):
        return _bishop.SphereVolume_eval(self, P)

    def grad(self, P):
        return _bishop.SphereVolume_grad(self, P)

    def typelabel(self):
        return _bishop.SphereVolume_typelabel(self)

# Register SphereVolume in _bishop:
_bishop.SphereVolume_swigregister(SphereVolume)

class ConstantVectorVolume(VectorVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, v):
        _bishop.ConstantVectorVolume_swiginit(self, _bishop.new_ConstantVectorVolume(v))
    __swig_destroy__ = _bishop.delete_ConstantVectorVolume

    def eval(self, P):
        return _bishop.ConstantVectorVolume_eval(self, P)

    def grad(self, P):
        return _bishop.ConstantVectorVolume_grad(self, P)

    def typelabel(self):
        return _bishop.ConstantVectorVolume_typelabel(self)

# Register ConstantVectorVolume in _bishop:
_bishop.ConstantVectorVolume_swigregister(ConstantVectorVolume)

class AddVectorVolume(VectorVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.AddVectorVolume_swiginit(self, _bishop.new_AddVectorVolume(*args))
    __swig_destroy__ = _bishop.delete_AddVectorVolume

    def eval(self, P):
        return _bishop.AddVectorVolume_eval(self, P)

    def grad(self, P):
        return _bishop.AddVectorVolume_grad(self, P)

    def typelabel(self):
        return _bishop.AddVectorVolume_typelabel(self)

# Register AddVectorVolume in _bishop:
_bishop.AddVectorVolume_swigregister(AddVectorVolume)

class GradientVectorVolume(VectorVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.GradientVectorVolume_swiginit(self, _bishop.new_GradientVectorVolume(*args))
    __swig_destroy__ = _bishop.delete_GradientVectorVolume

    def eval(self, P):
        return _bishop.GradientVectorVolume_eval(self, P)

    def grad(self, P):
        return _bishop.GradientVectorVolume_grad(self, P)

    def typelabel(self):
        return _bishop.GradientVectorVolume_typelabel(self)

# Register GradientVectorVolume in _bishop:
_bishop.GradientVectorVolume_swigregister(GradientVectorVolume)

class ConstantColor(ColorVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, v):
        _bishop.ConstantColor_swiginit(self, _bishop.new_ConstantColor(v))
    __swig_destroy__ = _bishop.delete_ConstantColor

    def eval(self, P):
        return _bishop.ConstantColor_eval(self, P)

    def typelabel(self):
        return _bishop.ConstantColor_typelabel(self)

# Register ConstantColor in _bishop:
_bishop.ConstantColor_swigregister(ConstantColor)

class AddColor(ColorVolume):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _bishop.AddColor_swiginit(self, _bishop.new_AddColor(*args))
    __swig_destroy__ = _bishop.delete_AddColor

    def eval(self, P):
        return _bishop.AddColor_eval(self, P)

    def typelabel(self):
        return _bishop.AddColor_typelabel(self)

# Register AddColor in _bishop:
_bishop.AddColor_swigregister(AddColor)


def evaluate(*args):
    return _bishop.evaluate(*args)

def constant(*args):
    return _bishop.constant(*args)

def add(*args):
    return _bishop.add(*args)

def Sphere(cen, rad):
    return _bishop.Sphere(cen, rad)

def cross_product(v1, v2):
    return _bishop.cross_product(v1, v2)

def dot_product(v1, v2):
    return _bishop.dot_product(v1, v2)

def __mul__(*args):
    return _bishop.__mul__(*args)

def mat_prod_vec(m, v):
    return _bishop.mat_prod_vec(m, v)

def vec_prod_mat(v, m):
    return _bishop.vec_prod_mat(v, m)

def __and__(v1, v2):
    return _bishop.__and__(v1, v2)

def outer_product(v1, v2, m):
    return _bishop.outer_product(v1, v2, m)

def exp(*args):
    return _bishop.exp(*args)

def sinch(m):
    return _bishop.sinch(m)

def inverse(m):
    return _bishop.inverse(m)

def det(m):
    return _bishop.det(m)

def trace(m):
    return _bishop.trace(m)

def rotation(*args):
    return _bishop.rotation(*args)

def unitMatrix():
    return _bishop.unitMatrix()

def Pauli0():
    return _bishop.Pauli0()

def Pauli1():
    return _bishop.Pauli1()

def Pauli2():
    return _bishop.Pauli2()


